name: Run Tests

on:
  workflow_run:
    workflows: ["build-and-deploy"]
    types:
      - completed

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Init Playwright
        run: npm init playwright@latest

      - name: Install Playwright/test
        run: npm install --save-dev @playwright/test

      - name: Install Playwright Browser
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test --trace on

      - name: Upload Trace File
        uses: actions/upload-artifact@v2
        with:
          name: trace
          path: test-results

      - name: Cleanup
        run: rm -rf node_modules
