name: Test

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps: 

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Current Working Directory
        run: |
          echo "Current working directory: $(pwd)"

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright
        run: npm init playwright@latest

      - name: Install Playwright/test
        run:  npm install --save-dev @playwright/test

      - name: Install Playwright
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Run Playwright Tests 2
        run: npx playwright test tests

      - name: Debug Test Information
        run: npx playwright test --list

      - name: Cleanup
        run: rm -rf node_modules
